name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - main



permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout
jobs:
  Deployment:
    name: Deplopyment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: print variables
        run: |
          echo input enviornment =  ${{ inputs.environment }}
          echo AWS_REGION = ${{ vars.ENVIRONMENT_NAME }}
          echo AWS_REGION = ${{ vars.AWS_REGION }}          
          echo AWS_REGION from repo = ${{ vars.AWS_REGION }}
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: AWS Account to assume
        run: |
          aws sts get-caller-identity

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}

      - name: Install CDK dependencies
        working-directory: ./
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Deploy CDK stack
        working-directory: ./
        run: |
          export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')
          npx cdk deploy --require-approval never
        env:
          AWS_REGION: ${{ vars.AWS_GITHUB_ROLE }}
